[package]
name = "ion"
version = "0.1.3"
description = "a parser for ion files"
license = "MIT"
homepage = "http://github.com/pzol/ion_rs"
repository = "http://github.com/pzol/ion_rs"
authors = ["Piotr Zolnierek <pzolnierek@gmail.com>"]

[dependencies]
docopt = "^0.6.73"
rustc-serialize = "^0.3.16"
