[package]
name = "ion"
version = "0.1.1"
description = "a parser for ion files"
license = "MIT"
homepage = "http://github.com/pzol/ion_rs"
repository = "http://github.com/pzol/ion_rs"
authors = ["Piotr Zolnierek <pzolnierek@gmail.com>"]

[dependencies]
docopt = "*"
rustc-serialize = "*"
