[package]
name = "ion"
version = "0.4.0"
description = "parse and process ion files"
license = "MIT"
homepage = "http://github.com/pzol/ion_rs"
repository = "http://github.com/pzol/ion_rs"
authors = ["Piotr Zolnierek <pzolnierek@gmail.com>"]

[dependencies]
docopt = "^0.6.73"
rustc-serialize = "^0.3"
